  # docker-compose.yaml
version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
    - 8080:8080
    - 50000:50000
    container_name: jenkins
    volumes:
    - /home/reagangcp/jenkins_compose/jenkins_configuration:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
  agent:
    image: jenkins/ssh-agent:jdk11
    privileged: true
    user: root
    container_name: agent
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC/JFbW1M8J6zuZxg3QVTgGb8ZfManUVRzRj5aUD9ND8Pnn0aZwdaBNhKCXbQL7VJiEqShHyHKoglRouTDGI5yNQ6YCnE1dgATnS1QIhmLtb26rryHzunlY90Xv8q/If4TY5p4NRKfSVqUvhUvj9GH0N+E9Pa/oUMApz15ju/GDDNDdaI7/mUtxsYqzhl2knLbKKsnwdig69c6Rm/TocCayALNRMO5dtA6Hx4ftLAZf+hP/u//djLh9T4FlRKHuYkWxRyD2DDx56x9Ov+y71FSj7fY5Hkz5xYrhbSgR3sSzMSR7d6syr1jOHF8Hsa2LyGhGfp1vhjIEtkSFSUL2VfwDWIuIlZoqcxeYWkhHJjMS7EYoT4W0hSCBHyQYCvfD4VV0emZHHQCStRvvP2Ct6QpCJDWN7g09NWv4pYOhlrdEWkHS59Z+zDnmbQzTz+aogM6V0kxxMql6goQU/3wjCgCKPKAnESRz+65aFZrouow0d0RluvAD/uXcDg/i+L2MOPc= reagangcp@jenkins-host